### ISSUE TITLE
truecrypt not compiling

### ISSUE THREAD

**Issue by qvacua** [DomT4/homebrew-crypto#2]
When I `brew install truecrypt`, I get the following error
```
==> Installing truecrypt from domt4/homebrew-crypto
==> Downloading https://github.com/DomT4/truecrypt-homebrew/releases/download/v1.1/Truecryptv1-1.tar.gz
Already downloaded: /Library/Caches/Homebrew/truecrypt-1.1.tar.gz
==> make -j8
Compiling Resources.cpp
Linking TrueCrypt
Error: TestFailed at TrueCrypt::TestCipher:181
make[1]: *** [TrueCrypt] Error 1
make: *** [all] Error 2
```
The dependencies install fine.

(I've installed osxfuse 2.7.5.)

**Comment by DomT4** [comment]
Hmm. Reproducible. Likely means one of the deps was upgraded beyond compatibility with Truecrypt. Will have a hunt around.

**Comment by qvacua** [comment]
It seems that "only" tests are broken. When I run `main/TrueCrypt`, it runs and seems to work fine. The app bundle does not get built though.

**Comment by DomT4** [comment]
Having trouble with container generation as well. I killed the tests and it built fine, and then tried to create a new container and hit that error again. I thought the problem was ` nasm ` but no dice on changing up those versions, so perhaps not. Will keep hunting.

**Comment by qvacua** [comment]
Thank you very much! :smile:

(I only mounted existing volumes....)

**Comment by DomT4** [comment]
The error on container creation extends to the CLI as well:

```
Enter keyfile path [none]:

Please type at least 320 randomly chosen characters and then press Enter:
Characters remaining: 254
Characters remaining: 124
Characters remaining: 14

Error: TestFailed at TrueCrypt::TestCipher:181
```

Which in a way makes it somewhat easier to track down. If it'd killed the GUI container creation but not the CLI container creation I'd have been chasing my metaphorical foot for weeks. It's interesting mounting existing volumes is working - That would hint that Truecrypt is still able to handle the decryption element at least.

**Comment by DomT4** [comment]
I've narrowed down the issue to one file, but not one test yet - To my complete frustration. If your need is urgent, I recommend [Veracrypt](http://sourceforge.net/projects/veracrypt/) as a decent alternative - It supports Truecrypt's container format, and is also open-source.
