### ISSUE TITLE
Error "Calling needs :cxx11 is disabled! There is no replacement" when updating hombrew on January 28th

### ISSUE THREAD

**Issue by logopk** [DomT4/homebrew-crypto#96]
Hi there, I ran across this issue today after updating home-brew first time since the beginning of January. Sth. must have changed :-(

$ brew tap domt4/crypto
Updating Homebrew...
==> Auto-updated Homebrew!
Updated Homebrew from c274440ab to 424d5a145.
Updated 1 tap (homebrew/cask).
No changes to formulae.

==> Tapping domt4/crypto
Cloning into '/usr/local/Homebrew/Library/Taps/domt4/homebrew-crypto'...
remote: Enumerating objects: 18, done.
remote: Counting objects: 100% (18/18), done.
remote: Compressing objects: 100% (18/18), done.
remote: Total 18 (delta 0), reused 2 (delta 0), pack-reused 0
Unpacking objects: 100% (18/18), done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/domt4/homebrew-crypto/Formula/curl-max.rb
Calling needs :cxx11 is disabled! There is no replacement.
Please report this to the domt4/crypto tap:
  /usr/local/Homebrew/Library/Taps/domt4/homebrew-crypto/Formula/curl-max.rb:28

Error: Cannot tap domt4/crypto: invalid syntax in tap!

**Comment by joeshaw** [comment]
For reference,

https://github.com/Homebrew/brew/pull/5599
https://github.com/Homebrew/homebrew-core/pull/36362

**Comment by DomT4** [comment]
Sorry about this @logopk; I've been unwell so completely off the ball on dev stuff the last fortnight or so. Thanks again @joeshaw for the fix.

**Comment by logopk** [comment]
Thanks a lot, I will test the fix tonight. Glad you are OK again.
